/* vim: set sw=4 sts=4 et foldmethod=syntax : */

/*
 * Copyright (c) 2022 Viktor Kuschke
 *
 * This file is part of the EOS project. EOS is free software;
 * you can redistribute it and/or modify it under the terms of the GNU General
 * Public License version 2, as published by the Free Software Foundation.
 *
 * EOS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59.0 Temple
 * Place, Suite 330, Boston, MA  02111-1307.0  USA
 */

#include <iostream>

#include <eos/maths/power-of.hh>
#include <eos/maths/polylog.hh>
#include <eos/maths/multiplepolylog-li22.hh>

#include <eos/rare-b-decays/charm-loops-impl.hh>

#include <eos/utils/exception.hh>
#include <eos/utils/log.hh>
#include <eos/utils/stringify.hh>

#include <cmath>
#include <complex>

namespace eos
{
    using std::complex;
    using std::log;

    namespace agv_2019a
    {
        // The following terms are the GPLs of weight 4 from f27d and f29d.
        // These are identical for the two functions, up to a global polynomial prefactor.
        complex<double> GPLweight4Parts(const CharmLoopsParameters & clp)
        {
            const complex<double> xd = clp.x_d;
            const complex<double> yd = clp.y_d;

            //if (std::abs(xd) > 1.0 || std::abs(yd) > 1.0)
            //{
            //    throw InternalError("The variables s =  " + std::to_string(std::real(clp.s_eps)) + " + i * " + std::to_string(imag(clp.s_eps)) + ",\n or z = " + std::to_string(std::real(clp.z_eps)) + " i * " + std::to_string(imag(clp.z_eps)) +  ", don't lie in the domain of definition of the GPLs");
            //}

            const complex<double> xdinv = 1.0 / xd;
            const complex<double> ydinv = 1.0 / yd;

            const complex<double> xd2 = power_of<2>(xd);
            const complex<double> xd4 = power_of<4>(xd);

            // weights appearing in the GPLs [AGV:2019A] p. 34

            const complex<double> w4 = (2.0 * xd) / power_of<2>(1.0 - xd);
            const complex<double> w5 = (2.0 * xd) / power_of<2>(1.0 + xd);
            const complex<double> w7 = (8.0 * xd2) / (1.0 - 6.0 * xd2 + xd4);

            const double imydinv = imag(ydinv);

            // often apperaing logs of xd and yd

            const complex<double> ln1pyd = log(1.0 + yd);
            const complex<double> ln1myd = log(1.0 - yd);

            // weight 4 GPLs

            // HPLs from F27(9)d that are free from problematic HeavisideTheta(0)
            const complex<double> w4Part1 = (-2.0 * power_of<4>(M_PI)) / 3.0 + 3.0 * power_of<2>(li2half) + (3.0 * power_of<2>(dilog((1.0 - yd) / 2.0))) / 2.0 + (9.0 * power_of<2>(dilog(-yd))) / 2.0 + (9.0 * power_of<2>(dilog(yd))) / 2.0 + (3.0 * power_of<2>(dilog((1.0 + yd) / 2.0))) / 2.0 - 6.0 * quadlog(-1.0) + 18.0 * quadlog(0.5) - 6.0 * quadlog(2.0)
                + 8.0 * quadlog(0.5 - (myi / 2.0) * xd) + 24.0 * quadlog(1.0 - myi * xd) + 8.0 * quadlog(1.0 / (1.0 + myi * xd)) + 8.0 * quadlog(2.0 / (1.0 + myi * xd)) + 8.0 * quadlog((1.0 + myi * xd) / 2.0) + 24.0 * quadlog(1.0 + myi * xd) + 8.0 * quadlog((-myi) * xd) + 8.0 * quadlog(myi * xd)
                + 16.0 * quadlog(-myi / (-myi + xd)) + 24.0 * quadlog(xd / (-myi + xd)) + 24.0 * quadlog(myi / (myi + xd)) + 8.0 * quadlog((2.0 * myi) / (myi + xd)) + 24.0 * quadlog(xd / (myi + xd)) + 8.0 * quadlog((-myi + xd) / (myi + xd)) + 8.0 * quadlog((myi + xd) / (-myi + xd))
                - 3.0 * quadlog(1.0 / (1.0 - yd)) - 17.0 * quadlog((1.0 - yd) / 2.0) - 15.0 * quadlog(1.0 - yd) - 5.0 * quadlog(-2.0 / (-1.0 + yd)) - 2.0 * quadlog(-yd) - 2.0 * quadlog(yd) - 3.0 * quadlog(yd / (-1.0 + yd)) - 3.0 * quadlog(1.0 / (1.0 + yd)) - 5.0 * quadlog(2.0 / (1.0 + yd))
                - 5.0 * quadlog((-1.0 + yd) / (1.0 + yd)) - 3.0 * quadlog(yd / (1.0 + yd)) - 17.0 * quadlog((1.0 + yd) / 2.0) - 15.0 * quadlog(1.0 + yd) - 5.0 * quadlog((1.0 + yd) / (-1.0 + yd)) - 4.0 * li22(-1.0, (-myi) * xd) - 4.0 * li22(-1.0, myi * xd) - li22(-1.0, -yd) / 2.0
                - li22(-1.0, yd) / 2.0 - 16.0 * li22((-myi) * xd, -1.0) + 4.0 * li22((-myi) * xd, -myi / xd) - 16.0 * li22(myi * xd, -1.0) + 4.0 * li22(myi * xd, myi / xd) - 2.0 * li22(-yd, -1.0) + li22(-yd, ydinv) / 2.0 - 2.0 * li22(yd, -1.0) + li22(yd, -ydinv) / 2.0
                + (pisqu * power_of<2>(lnhalf)) / 2.0 + lnmhalf * power_of<3>(lnhalf) - power_of<4>(lnhalf) / 2.0 - (4.0 * log(-0.5 - (myi / 2.0) * xd) * power_of<3>(log(0.5 - (myi / 2.0) * xd))) / 3.0 + (2.0 * power_of<4>(log(0.5 - (myi / 2.0) * xd))) / 3.0 + (7.0 * power_of<4>(log(1.0 - myi * xd))) / 3.0
                - (2.0 * pisqu * power_of<2>(log((1.0 + myi * xd) / 2.0))) / 3.0 + (2.0 * power_of<4>(log((1.0 + myi * xd) / 2.0))) / 3.0 + (4.0 * log(1.0 - myi * xd) * power_of<3>(log(1.0 + myi * xd))) / 3.0 + (7.0 * power_of<4>(log(1.0 + myi * xd))) / 3.0
                + power_of<2>(log(0.5 - (myi / 2.0) * xd)) * ((-2.0 * pisqu) / 3.0 - 4.0 * log((1.0 + myi * xd) / 2.0) * log(1.0 + myi * xd) - 2.0 * power_of<2>(log(1.0 + myi * xd)))
                + dilog(0.5 - (myi / 2.0) * xd) * (-8.0 * log(0.5 - (myi / 2.0) * xd) * log(1.0 + myi * xd) + log(1.0 - myi * xd) * (-8.0 * log((1.0 + myi * xd) / 2.0) + 8.0 * log(1.0 + myi * xd) - 8.0 * log(xd)))
                + power_of<3>(log(1.0 + myi * xd)) * (-4.0 * log((-myi) * xd) - 4.0 * log(myi * xd) - (4.0 * log(xd)) / 3.0) + power_of<3>(log(1.0 - myi * xd)) * ((4.0 * log(1.0 + myi * xd)) / 3.0 - 4.0 * log((-myi) * xd) - 4.0 * log(myi * xd) - (4.0 * log(xd)) / 3.0) - 16.0 * trilog(-1.0) * log(xd)
                + 8.0 * trilog(0.5 + (myi / 2.0) * xd) * log(xd) + 8.0 * trilog(-myi / (-myi + xd)) * log(xd) - 8.0 * trilog((-myi + xd) / (2.0 * xd)) * log(xd) + 8.0 * trilog(myi / (myi + xd)) * log(xd) - 8.0 * trilog((myi - xd) / (myi + xd)) * log(xd)
                + 8.0 * trilog((-myi + xd) / (myi + xd)) * log(xd) + 8.0 * trilog(((-0.5) * myi) * (myi + xd)) * log(xd) - 8.0 * trilog((myi + xd) / (myi - xd)) * log(xd) - 8.0 * trilog((myi + xd) / (2.0 * xd)) * log(xd)
                + 8.0 * trilog((myi + xd) / (-myi + xd)) * log(xd) + 8.0 * dilog((myi + xd) / (myi - xd)) * log(1.0 - myi * xd) * log(xd) + 8.0 * dilog((myi + xd) / (2.0 * xd)) * log(1.0 - myi * xd) * log(xd)
                - 8.0 * dilog((myi + xd) / (-myi + xd)) * log(1.0 - myi * xd) * log(xd) + 8.0 * dilog((-myi + xd) / (2.0 * xd)) * log(1.0 + myi * xd) * log(xd) + 8.0 * dilog((myi - xd) / (myi + xd)) * log(1.0 + myi * xd) * log(xd)
                - 8.0 * dilog((-myi + xd) / (myi + xd)) * log(1.0 + myi * xd) * log(xd) + trilog(1.0 - myi * xd) * (-8.0 * log(1.0 - myi * xd) + 8.0 * log(xd)) + trilog(1.0 + myi * xd) * (-8.0 * log(1.0 + myi * xd) + 8.0 * log(xd))
                + trilog((-myi) * xd) * (16.0 * log(1.0 - myi * xd) - 8.0 * log(1.0 + myi * xd) + 8.0 * log(xd)) + trilog(myi * xd) * (-8.0 * log(1.0 - myi * xd) + 16.0 * log(1.0 + myi * xd) + 8.0 * log(xd))
                + dilog(1.0 - myi * xd) * (-4.0 * power_of<2>(log(1.0 - myi * xd)) - 8.0 * log(1.0 - myi * xd) * log(xd)) + dilog(myi * xd) * (-4.0 * power_of<2>(log(1.0 - myi * xd)) - 8.0 * log(1.0 - myi * xd) * log(xd))
                + dilog(1.0 + myi * xd) * (-4.0 * power_of<2>(log(1.0 + myi * xd)) - 8.0 * log(1.0 + myi * xd) * log(xd)) + dilog((-myi) * xd) * (16.0 * dilog(myi * xd) - 4.0 * power_of<2>(log(1.0 + myi * xd)) - 8.0 * log(1.0 + myi * xd) * log(xd))
                + dilog((1.0 + myi * xd) / 2.0) * (-8.0 * log(0.5 - (myi / 2.0) * xd) * log(1.0 + myi * xd) + log(1.0 - myi * xd) * (-8.0 * log((1.0 + myi * xd) / 2.0) + 8.0 * log(1.0 + myi * xd)) - 8.0 * log(1.0 + myi * xd) * log(xd))
                + dilog(-1.0) * (-4.0 * dilog((-myi) * xd) - 4.0 * dilog(myi * xd) - dilog(-yd) / 2.0 - dilog(yd) / 2.0 - 8.0 * log(1.0 - myi * xd) * log(xd) - 8.0 * log(1.0 + myi * xd) * log(xd))
                + power_of<2>(log(1.0 - myi * xd)) * (-2.0 * pisqu - 2.0 * power_of<2>(log((1.0 + myi * xd) / 2.0)) + log((1.0 + myi * xd) / 2.0) * (4.0 * log(1.0 + myi * xd) - 4.0 * log(xd)) - 4.0 * log(myi * xd) * log(xd)
                + log(xd) * (-4.0 * log((-2.0 * myi) / (-myi + xd)) + 4.0 * log((2.0 * xd) / (-myi + xd)) + 4.0 * log((-myi + xd) / (2.0 * xd)))) - (4.0 * power_of<3>(log((1.0 + myi * xd) / 2.0)) * log((myi / 2.0) * (myi + xd))) / 3.0
                + power_of<2>(log(1.0 + myi * xd)) * (-2.0 * pisqu - 4.0 * log((-myi) * xd) * log(xd) + log(xd) * (-4.0 * log((2.0 * myi) / (myi + xd)) + 4.0 * log((2.0 * xd) / (myi + xd)) + 4.0 * log((myi + xd) / (2.0 * xd)))) + (5.0 * log((-1.0 - yd) / 2.0) * power_of<3>(log((1.0 - yd) / 2.0))) / 6.0
                - (5.0 * power_of<4>(log((1.0 - yd) / 2.0))) / 12.0 + 12.0 * trilog(1.0 - yd) * ln1myd - (9.0 * dilog(1.0 - yd) * power_of<2>(ln1myd)) / 2.0 - (dilog(yd) * power_of<2>(ln1myd)) / 2.0 - power_of<4>(ln1myd) / 4.0
                + power_of<3>(ln1myd) * (log(-yd) / 2.0 - log(yd) + log((1.0 + yd) / 2.0) / 2.0) + (5.0 * pisqu * power_of<2>(log((1.0 + yd) / 2.0))) / 12.0 + (5.0 * log((-1.0 + yd) / 2.0) * power_of<3>(log((1.0 + yd) / 2.0))) / 6.0 - (5.0 * power_of<4>(log((1.0 + yd) / 2.0))) / 12.0
                + trilog(yd) * (10.0 * ln1myd - 7.0 * ln1pyd) + trilog((1.0 - yd) / 2.0) * (2.0 * ln1myd - 2.0 * ln1pyd) + 12.0 * trilog(1.0 + yd) * ln1pyd + (pisqu * power_of<2>(ln1pyd)) / 4.0
                - (9.0 * dilog(1.0 + yd) * power_of<2>(ln1pyd)) / 2.0 - log(-yd) * power_of<3>(ln1pyd) + (log(yd) * power_of<3>(ln1pyd)) / 2.0 - power_of<4>(ln1pyd) / 4.0 + trilog((1.0 + yd) / 2.0) * (-2.0 * ln1myd + 2.0 * ln1pyd)
                + li3half * (6.0 * lnhalf - 8.0 * log(0.5 - (myi / 2.0) * xd) + 8.0 * log(1.0 - myi * xd) - 8.0 * log((1.0 + myi * xd) / 2.0) + 8.0 * log(1.0 + myi * xd) - 16.0 * log(xd) + 5.0 * log((1.0 - yd) / 2.0) + 7.0 * ln1myd + 5.0 * log((1.0 + yd) / 2.0)
                + 7.0 * ln1pyd) + trilog(-yd) * (-7.0 * ln1myd + 10.0 * ln1pyd) + dilog((1.0 - yd) / 2.0) * ((3.0 * power_of<2>(ln1myd)) / 2.0 + ln1myd * (8.0 * log((1.0 + yd) / 2.0) - 3.0 * ln1pyd)
                + 5.0 * log((1.0 - yd) / 2.0) * ln1pyd) + power_of<2>(ln1myd) * (pisqu / 4.0 + (11.0 * power_of<2>(log((1.0 + yd) / 2.0))) / 4.0 - (3.0 * log((1.0 + yd) / 2.0) * ln1pyd) / 2.0) + dilog(-yd) * (-7.0 * dilog(yd) - power_of<2>(ln1pyd) / 2.0)
                + dilog((1.0 + yd) / 2.0) * (ln1myd * (5.0 * log((1.0 + yd) / 2.0) - 3.0 * ln1pyd) + 8.0 * log((1.0 - yd) / 2.0) * ln1pyd + (3.0 * power_of<2>(ln1pyd)) / 2.0)
                + li2half * (-3.0 * dilog((1.0 - yd) / 2.0) - 3.0 * dilog((1.0 + yd) / 2.0) + (5.0 * power_of<2>(ln1myd)) / 2.0 - 3.0 * ln1myd * log((1.0 + yd) / 2.0) - 3.0 * log((1.0 - yd) / 2.0) * ln1pyd + (5.0 * power_of<2>(ln1pyd)) / 2.0)
                + power_of<2>(log((1.0 - yd) / 2.0)) * ((5.0 * pisqu) / 12.0 + (5.0 * log((1.0 + yd) / 2.0) * ln1pyd) / 2.0 + (11.0 * power_of<2>(ln1pyd)) / 4.0) + log(xd) * ((-4.0 * pisqu * log(((-0.5) * myi) * xdinv)) / 3.0 - (4.0 * power_of<3>(log(((-0.5) * myi) * xdinv))) / 3.0
                - (4.0 * pisqu * log(myi / 2.0 * xdinv)) / 3.0 - (4.0 * power_of<3>(log(myi / 2.0 * xdinv))) / 3.0 + (4.0 * pisqu * log(-myi / (-myi + xd))) / 3.0 + (4.0 * power_of<3>(log(-myi / (-myi + xd)))) / 3.0 + (4.0 * pisqu * log(myi / (myi + xd))) / 3.0 + (4.0 * power_of<3>(log(myi / (myi + xd)))) / 3.0 - 16.0 * zeta3)
                + log((1.0 - yd) / 2.0) * (power_of<3>(ln1pyd) / 2.0 + ln1myd * ((5.0 * power_of<2>(log((1.0 + yd) / 2.0))) / 2.0 - (3.0 * power_of<2>(ln1pyd)) / 2.0) - 5.0 * zeta3) - 6.0 * lnhalf * zeta3 + 8.0 * log((1.0 + myi * xd) / 2.0) * zeta3 + 5.0 * ln1myd * zeta3
                - 5.0 * log((1.0 + yd) / 2.0) * zeta3 + 5.0 * ln1pyd * zeta3 + log(0.5 - (myi / 2.0) * xd) * (log(1.0 - myi * xd) * (-4.0 * power_of<2>(log((1.0 + myi * xd) / 2.0)) + 4.0 * power_of<2>(log(1.0 + myi * xd))) - 4.0 * power_of<2>(log(1.0 + myi * xd)) * log(xd) + 8.0 * zeta3);

            //GPLs form F27(9)d with at least one weight being +-wx3
            const complex<double> w4Part2 = weight4_wx3_wx4(clp, wx3) + weight4_wx3_wx4(clp, -wx3);

            //GPLs form F27(9)d with at least one weight being +-wx4
            const complex<double> w4Part3 = weight4_wx3_wx4(clp, wx4) + weight4_wx3_wx4(clp, -wx4);

            //GPLs form F27(9)d with at least one weight being +-w4
            const complex<double> w4Part4 = weight4_w4_w5_w7(clp, w4);

            //GPLs form F27(9)d with at least one weight being +-w5
            const complex<double> w4Part5 = weight4_w4_w5_w7(clp, -w5);

            //GPLs form F27(9)d with at least one weight being +-w7
            const complex<double> w4Part6 = - 0.25 * weight4_w4_w5_w7(clp, w7);

            // Weight 4 HPLs where the weights are a permutation of {a, a, -a, 0}.
            // In order to make the expressions well defined, the replacement -a -> -a * (1 + i eta) was made
            const double eta = 1e-13;

            const complex<double> w4HPLs = (-4.0 * power_of<4>(M_PI)) / 3.0 + 3.0 * power_of<2>(dilog(2.0)) - (3.0 * power_of<2>(dilog(1.0 / (2.0 - myi * eta)))) / 2.0 - 9.0 * power_of<2>(dilog(2.0 - myi * eta)) - (51.0 * power_of<2>(dilog(myi / (2.0 * myi + eta)))) / 2.0 - 18.0 * quadlog(2.0) + 18.0 * quadlog(1.0 + 1.0 / (1.0 - myi * eta)) - 3.0 * quadlog(1.0 / (2.0 - myi * eta)) + 90.0 * quadlog(2.0 - myi * eta) + 18.0 * quadlog(1.0 / (-1.0 + myi * eta)) + 18.0 * quadlog(-myi / (myi + eta)) + 93.0 * quadlog(myi / (2.0 * myi + eta)) + 18.0 * quadlog((2.0 * myi + eta) / (myi + eta)) + 24.0 * quadlog(1.0 - myi * xd) + 24.0 * quadlog(1.0 + myi * xd) + 2.0 * quadlog(1.0 - yd) + 8.0 * quadlog((-1.0 + yd) / (-2.0 + myi * eta)) + 2.0 * quadlog(1.0 + yd) + 8.0 * quadlog((myi * (1.0 + yd)) / (2.0 * myi + eta))
                - 4.0 * li22(1.0 / (2.0 - myi * eta), 1.0 + yd) - 12.0 * li22(2.0 - myi * eta, (myi - xd) / (2.0 * myi + eta)) - 12.0 * li22(2.0 - myi * eta, (myi + xd) / (2.0 * myi + eta)) - li22(2.0 - myi * eta, (-1.0 + yd) / (-2.0 + myi * eta)) - li22(2.0 - myi * eta, (myi * (1.0 + yd)) / (2.0 * myi + eta)) - 4.0 * li22(myi / (2.0 * myi + eta), 1.0 - yd) - 20.0 * li22((myi - xd) / (2.0 * myi + eta), 2.0 - myi * eta) + 8.0 * li22(0.5 - (myi / 2.0) * xd, 2.0) - 12.0 * li22(1.0 - myi * xd, myi / (2.0 * myi + eta)) + 12.0 * li22(1.0 - myi * xd, (2.0 * myi + eta) / (myi + xd)) + 8.0 * li22((1.0 + myi * xd) / 2.0, 2.0) - 12.0 * li22(1.0 + myi * xd, myi / (2.0 * myi + eta)) + 12.0 * li22(1.0 + myi * xd, (2.0 * myi + eta) / (myi - xd))
                - 20.0 * li22((myi + xd) / (2.0 * myi + eta), 2.0 - myi * eta) - 5.0 * li22((1.0 - yd) / 2.0, 2.0) - 10.0 * li22(1.0 - yd, myi / (2.0 * myi + eta)) + li22(1.0 - yd, (myi * (2.0 * myi + eta)) / (-1.0 + yd)) - 2.0 * li22((-1.0 + yd) / (-2.0 + myi * eta), 2.0 - myi * eta) + 4.0 * li22((-1.0 + yd) / (-2.0 + myi * eta), 1.0 / (1.0 - yd)) - 5.0 * li22((1.0 + yd) / 2.0, 2.0) - 10.0 * li22(1.0 + yd, 1.0 / (2.0 - myi * eta)) + li22(1.0 + yd, (2.0 - myi * eta) / (1.0 + yd)) - 2.0 * li22((myi * (1.0 + yd)) / (2.0 * myi + eta), 2.0 - myi * eta) + 4.0 * li22((myi * (1.0 + yd)) / (2.0 * myi + eta), 1.0 / (1.0 + yd)) + dilog(2.0) * (3.0 * pisqu + 3.0 * power_of<2>(lnm2)) + 3.0 * pisqu * power_of<2>(log(-1.0 + myi * eta))
                + 6.0 * log(-2.0 + myi * eta) * power_of<3>(log(-1.0 + myi * eta)) - 3.0 * power_of<4>(log(-1.0 + myi * eta)) - 6.0 * pisqu * power_of<2>(log((myi + eta) / (2.0 * myi + eta))) - 2.0 * log(1.0 / (-2.0 + myi * eta)) * power_of<3>(log((myi + eta) / (2.0 * myi + eta))) - 10.0 * log(-myi / (2.0 * myi + eta)) * power_of<3>(log((myi + eta) / (2.0 * myi + eta))) + 6.0 * power_of<4>(log((myi + eta) / (2.0 * myi + eta))) + trilog(1.0 - myi * xd) * (-24.0 * log(-1.0 + myi * eta) - 8.0 * log((myi + eta - xd) / (myi + eta)) + 24.0 * log((myi + eta - xd) / (2.0 * myi + eta)) - 24.0 * log(1.0 - myi * xd)) + 12.0 * trilog((myi + eta) / (myi + eta - xd)) * log(1.0 - myi * xd) + 24.0 * trilog((2.0 * myi + eta) / (myi + eta - xd)) * log(1.0 - myi * xd)
                - 12.0 * trilog(myi * xd) * log(1.0 - myi * xd) + 20.0 * trilog(xd / (myi + eta)) * log(1.0 - myi * xd) - 24.0 * trilog((myi * (2.0 * myi + eta) * xd) / (myi + eta - xd)) * log(1.0 - myi * xd) + 8.0 * trilog((-myi + xd) / (2.0 * xd)) * log(1.0 - myi * xd) + 4.0 * trilog(myi / (myi + xd)) * log(1.0 - myi * xd) - 4.0 * trilog((myi * (myi + eta - xd)) / ((myi + eta) * (myi + xd))) * log(1.0 - myi * xd) - 24.0 * trilog(((2.0 * myi + eta) * xd) / ((myi + eta) * (myi + xd))) * log(1.0 - myi * xd) + 8.0 * trilog((-myi + xd) / (myi + xd)) * log(1.0 - myi * xd) + 24.0 * trilog(xd / (-myi - eta + xd)) * log(1.0 - myi * xd) + 12.0 * trilog((myi + xd) / (-myi - eta + xd)) * log(1.0 - myi * xd)
                + 4.0 * trilog((-myi - eta + xd) * xdinv) * log(1.0 - myi * xd) - 4.0 * trilog((-myi - eta + xd) / (myi + xd)) * log(1.0 - myi * xd) - 12.0 * trilog((myi + eta + xd - myi * eta * xd) / (myi + eta - xd)) * log(1.0 - myi * xd) - 8.0 * trilog((1.0 - myi * eta + myi * xd) / ((2.0 * myi) * xd + eta * xd)) * log(1.0 - myi * xd) + 4.0 * pisqu * log(-myi / (myi + eta - xd)) * log(1.0 - myi * xd) + 4.0 * power_of<3>(log(-myi / (myi + eta - xd))) * log(1.0 - myi * xd) + 4.0 * dilog(myi * xd) * log((myi + eta - xd) / (myi + eta)) * log(1.0 - myi * xd) + 4.0 * dilog((myi * (myi + eta - xd)) / ((myi + eta) * (myi + xd))) * log((myi + eta - xd) / (myi + eta)) * log(1.0 - myi * xd)
                + 8.0 * dilog((1.0 - myi * eta + myi * xd) / ((2.0 * myi) * xd + eta * xd)) * log((myi + eta - xd) / (2.0 * myi + eta)) * log(1.0 - myi * xd) - 12.0 * dilog((myi + xd) / (-myi - eta + xd)) * power_of<2>(log(1.0 - myi * xd)) + 12.0 * dilog((myi + eta + xd - myi * eta * xd) / (myi + eta - xd)) * power_of<2>(log(1.0 - myi * xd)) + dilog((-myi - eta + xd) * xdinv) * (4.0 * log((myi + eta - xd) / (myi + eta)) * log(1.0 - myi * xd) - 8.0 * log((myi + eta - xd) / (2.0 * myi + eta)) * log(1.0 - myi * xd)) + dilog((-myi - eta + xd) / (myi + xd)) * (-4.0 * log((myi + eta - xd) / (myi + eta)) * log(1.0 - myi * xd) + 8.0 * log((myi + eta - xd) / (2.0 * myi + eta)) * log(1.0 - myi * xd))
                - 8.0 * dilog((-myi + xd) / (2.0 * xd)) * log(1.0 - myi * xd) * log((1.0 + myi * xd) / 2.0) - 8.0 * dilog((-myi + xd) / (myi + xd)) * log(1.0 - myi * xd) * log((1.0 + myi * xd) / 2.0) + trilog((-myi + xd) * xdinv) * (-8.0 * log(1.0 - myi * xd) - 12.0 * log(1.0 + myi * xd)) + trilog((myi + xd) * xdinv) * (-12.0 * log(1.0 - myi * xd) - 8.0 * log(1.0 + myi * xd)) - 12.0 * trilog((-myi) * xd) * log(1.0 + myi * xd) + 20.0 * trilog(-(xd / (myi + eta))) * log(1.0 + myi * xd) + 4.0 * trilog(-myi / (-myi + xd)) * log(1.0 + myi * xd) - 24.0 * trilog(((2.0 * myi + eta) * xd) / ((myi + eta) * (-myi + xd))) * log(1.0 + myi * xd) + 8.0 * trilog((myi + xd) / (2.0 * xd)) * log(1.0 + myi * xd)
                + 8.0 * trilog((myi + xd) / (-myi + xd)) * log(1.0 + myi * xd) + 12.0 * trilog((myi + eta) / (myi + eta + xd)) * log(1.0 + myi * xd) + 24.0 * trilog((2.0 * myi + eta) / (myi + eta + xd)) * log(1.0 + myi * xd) - 12.0 * trilog(((myi + eta) * (1.0 + myi * xd)) / (myi + eta + xd)) * log(1.0 + myi * xd) + 24.0 * trilog(xd / (myi + eta + xd)) * log(1.0 + myi * xd) - 24.0 * trilog(((2.0 - myi * eta) * xd) / (myi + eta + xd)) * log(1.0 + myi * xd) + 12.0 * trilog((-myi + xd) / (myi + eta + xd)) * log(1.0 + myi * xd) + 4.0 * trilog((myi + eta + xd) * xdinv) * log(1.0 + myi * xd) - 8.0 * trilog((myi * (myi + eta + xd)) / ((2.0 * myi + eta) * xd)) * log(1.0 + myi * xd)
                - 4.0 * trilog((myi + eta + xd) / (-myi + xd)) * log(1.0 + myi * xd) - 4.0 * trilog(((-myi) * (myi + eta + xd)) / ((myi + eta) * (-myi + xd))) * log(1.0 + myi * xd) + (2.0 * pisqu * log((myi + eta) / (myi - xd)) * log(1.0 + myi * xd)) / 3.0 + (2.0 * power_of<3>(log((myi + eta) / (myi - xd))) * log(1.0 + myi * xd)) / 3.0 - 8.0 * dilog((myi + xd) / (2.0 * xd)) * log(0.5 - (myi / 2.0) * xd) * log(1.0 + myi * xd) - 8.0 * dilog((myi + xd) / (-myi + xd)) * log(0.5 - (myi / 2.0) * xd) * log(1.0 + myi * xd) + 12.0 * dilog(((myi + eta) * (1.0 + myi * xd)) / (myi + eta + xd)) * power_of<2>(log(1.0 + myi * xd)) - 12.0 * dilog((-myi + xd) / (myi + eta + xd)) * power_of<2>(log(1.0 + myi * xd))
                + dilog((myi + xd) * xdinv) * (12.0 * power_of<2>(log(1.0 - myi * xd)) + 8.0 * log(0.5 - (myi / 2.0) * xd) * log(1.0 + myi * xd)) + dilog((-myi + xd) * xdinv) * (8.0 * log(1.0 - myi * xd) * log((1.0 + myi * xd) / 2.0) + 12.0 * power_of<2>(log(1.0 + myi * xd))) + trilog((1.0 + myi * xd) / 2.0) * (8.0 * log(1.0 + myi * xd) - 16.0 * log((-myi) * xd)) + 24.0 * dilog(((2.0 * myi + eta) * xd) / ((myi + eta) * (-myi + xd))) * log(1.0 + myi * xd) * log((-myi) * xd) - 24.0 * dilog(xd / (myi + eta + xd)) * log(1.0 + myi * xd) * log((-myi) * xd) + 24.0 * dilog(((2.0 - myi * eta) * xd) / (myi + eta + xd)) * log(1.0 + myi * xd) * log((-myi) * xd)
                + trilog((myi - xd) / (2.0 * myi + eta)) * (24.0 * log(-1.0 + myi * eta) + 16.0 * log(1.0 + myi * xd) + 16.0 * log((-myi) * xd)) + dilog(-(xd / (myi + eta))) * (-12.0 * power_of<2>(log(1.0 + myi * xd)) - 24.0 * log(1.0 + myi * xd) * log((-myi) * xd)) + trilog(0.5 - (myi / 2.0) * xd) * (8.0 * log(1.0 - myi * xd) - 16.0 * log(myi * xd)) + 24.0 * dilog((myi * (2.0 * myi + eta) * xd) / (myi + eta - xd)) * log(1.0 - myi * xd) * log(myi * xd) + 24.0 * dilog(((2.0 * myi + eta) * xd) / ((myi + eta) * (myi + xd))) * log(1.0 - myi * xd) * log(myi * xd) - 24.0 * dilog(xd / (-myi - eta + xd)) * log(1.0 - myi * xd) * log(myi * xd)
                + trilog((myi + xd) / (2.0 * myi + eta)) * (24.0 * log(-1.0 + myi * eta) + 16.0 * log(1.0 - myi * xd) + 16.0 * log(myi * xd)) + dilog(xd / (myi + eta)) * (-12.0 * power_of<2>(log(1.0 - myi * xd)) - 24.0 * log(1.0 - myi * xd) * log(myi * xd)) + 4.0 * dilog((-myi) * xd) * log(1.0 + myi * xd) * log((myi + eta + xd) / (myi + eta)) + 4.0 * dilog(((-myi) * (myi + eta + xd)) / ((myi + eta) * (-myi + xd))) * log(1.0 + myi * xd) * log((myi + eta + xd) / (myi + eta)) + dilog((myi + eta + xd) * xdinv) * log(1.0 + myi * xd) * (4.0 * log((myi + eta + xd) / (myi + eta)) - 8.0 * log((myi + eta + xd) / (2.0 * myi + eta)))
                + 8.0 * dilog((myi * (myi + eta + xd)) / ((2.0 * myi + eta) * xd)) * log(1.0 + myi * xd) * log((myi + eta + xd) / (2.0 * myi + eta)) + dilog((myi + eta + xd) / (-myi + xd)) * log(1.0 + myi * xd) * (-4.0 * log((myi + eta + xd) / (myi + eta)) + 8.0 * log((myi + eta + xd) / (2.0 * myi + eta))) + trilog(1.0 + myi * xd) * (-24.0 * log(-1.0 + myi * eta) - 24.0 * log(1.0 + myi * xd) - 8.0 * log((myi + eta + xd) / (myi + eta)) + 24.0 * log((myi + eta + xd) / (2.0 * myi + eta))) - (3.0 * trilog(1.0 / (-1.0 + myi * eta)) * ln1myd) / 2.0 - 8.0 * trilog((2.0 * myi + eta) / (myi + eta)) * ln1myd - (trilog(1.0 / (1.0 - yd)) * ln1myd) / 2.0
                + 10.0 * trilog(ydinv) * ln1myd - 11.0 * trilog(((myi + eta) * (-1.0 + yd)) / ((2.0 * myi + eta) * yd)) * ln1myd - (15.0 * trilog(yd) * ln1myd) / 2.0 + (27.0 * trilog(yd / (-1.0 + myi * eta)) * ln1myd) / 2.0 - 5.0 * trilog(yd / (-1.0 + yd)) * ln1myd - 2.0 * trilog(((2.0 * myi + eta) * yd) / ((myi + eta) * (-1.0 + yd))) * ln1myd - 5.0 * trilog((1.0 + yd) / (-1.0 + yd)) * ln1myd - 5.0 * trilog((1.0 + yd) / (2.0 * yd)) * ln1myd + (15.0 * trilog((-1.0 + yd) / (1.0 - myi * eta + yd)) * ln1myd) / 2.0 + 7.0 * trilog(yd / (1.0 - myi * eta + yd)) * ln1myd
                + (5.0 * trilog((1.0 - myi * eta + yd) / (-1.0 + yd)) * ln1myd) / 2.0 + (11.0 * trilog((1.0 - myi * eta + yd) / yd) * ln1myd) / 2.0 + 8.0 * trilog(1.0 + (myi * yd) / (myi + eta)) * ln1myd + (15.0 * trilog((myi + eta) / (eta + myi * (1.0 + yd))) * ln1myd) / 2.0 + 7.0 * trilog((2.0 * myi + eta) / (eta + myi * (1.0 + yd))) * ln1myd - (15.0 * trilog(-(((myi + eta) * (-1.0 + yd)) / (eta + myi * (1.0 + yd)))) * ln1myd) / 2.0 - 7.0 * trilog(((2.0 * myi + eta) * yd) / (eta + myi * (1.0 + yd))) * ln1myd - (15.0 * trilog(-((eta + myi * (1.0 + yd)) / ((myi + eta) * (-1.0 + yd)))) * ln1myd) / 2.0
                - 5.0 * trilog((eta + myi * (1.0 + yd)) / ((2.0 * myi + eta) * yd)) * ln1myd - (5.0 * power_of<3>(log(1.0 / (1.0 - yd))) * ln1myd) / 6.0 + (3.0 * dilog(1.0 / (-1.0 + myi * eta)) * power_of<2>(ln1myd)) / 2.0 + 4.0 * dilog((2.0 * myi + eta) / (myi + eta)) * power_of<2>(ln1myd) + 11.0 * dilog(((myi + eta) * (-1.0 + yd)) / ((2.0 * myi + eta) * yd)) * power_of<2>(ln1myd) - (15.0 * dilog((-1.0 + yd) / (1.0 - myi * eta + yd)) * power_of<2>(ln1myd)) / 2.0 + (15.0 * dilog(-(((myi + eta) * (-1.0 + yd)) / (eta + myi * (1.0 + yd)))) * power_of<2>(ln1myd)) / 2.0 + dilog((-1.0 + yd) / (-2.0 + myi * eta)) * ((-5.0 * pisqu) / 6.0 + 11.0 * dilog(yd) - 11.0 * power_of<2>(ln1myd))
                + 5.0 * dilog(yd / (-1.0 + yd)) * ln1myd * log(yd) + 2.0 * dilog(((2.0 * myi + eta) * yd) / ((myi + eta) * (-1.0 + yd))) * ln1myd * log(yd) - 7.0 * dilog(yd / (1.0 - myi * eta + yd)) * ln1myd * log(yd) + 7.0 * dilog(((2.0 * myi + eta) * yd) / (eta + myi * (1.0 + yd))) * ln1myd * log(yd) + trilog((-1.0 + yd) / (-2.0 + myi * eta)) * (2.0 * log(-1.0 + myi * eta) - 8.0 * log((myi + eta) / (2.0 * myi + eta)) + 8.0 * ln1myd + 2.0 * log(yd)) + trilog((1.0 - yd) / 2.0) * (-5.0 * ln1myd + 10.0 * log(yd))
                + dilog(myi / (2.0 * myi + eta)) * ((-29.0 * pisqu) / 3.0 - 8.0 * dilog(1.0 - myi * xd) - 8.0 * dilog(1.0 + myi * xd) + 3.0 * dilog(1.0 - yd) - 4.0 * dilog((-1.0 + yd) / (-2.0 + myi * eta)) - 11.0 * dilog(-yd) + (3.0 * power_of<2>(log(1.0 / (-2.0 + myi * eta)))) / 2.0 - 12.0 * power_of<2>(log(-myi / (2.0 * myi + eta))) + (8.0 * log(1.0) - 16.0 * log(1.0 + myi * xd)) * log((-myi) * xd) + (8.0 * log(1.0) - 16.0 * log(1.0 - myi * xd)) * log(myi * xd) + (5.0 * log(1.0) - 2.0 * ln1myd) * log(yd)) + dilog(yd / (-1.0 + myi * eta)) * (-power_of<2>(ln1myd) - 2.0 * ln1myd * log(yd)) + log(1.0 / (1.0 - yd)) * ln1myd * ((-5.0 * pisqu) / 6.0 + (5.0 * power_of<2>(log(yd))) / 2.0)
                + 5.0 * dilog((1.0 + yd) / (-1.0 + yd)) * ln1myd * log((1.0 + yd) / 2.0) + 5.0 * dilog((1.0 + yd) / (2.0 * yd)) * ln1myd * log((1.0 + yd) / 2.0) + dilog(1.0 / (2.0 - myi * eta)) * ((7.0 * pisqu) / 3.0 - 11.0 * dilog(yd) + 3.0 * dilog(1.0 + yd) - 4.0 * dilog((myi * (1.0 + yd)) / (2.0 * myi + eta)) + (3.0 * power_of<2>(log(-myi / (2.0 * myi + eta)))) / 2.0 + log(-yd) * (5.0 * log(1.0) - 2.0 * ln1pyd)) + trilog(myi / (2.0 * myi + eta)) * (-42.0 * log(-1.0 + myi * eta) - 60.0 * log((myi + eta) / (2.0 * myi + eta)) - 8.0 * log(1.0 - myi * xd) - 8.0 * log(1.0 + myi * xd) - 16.0 * log((-myi) * xd) - 16.0 * log(myi * xd) - 5.0 * ln1myd - 2.0 * log(yd) - 11.0 * ln1pyd)
                + trilog(-1.0 + myi * eta) * (-12.0 * log(1.0 - myi * xd) - 12.0 * log(1.0 + myi * xd) - (15.0 * ln1myd) / 2.0 - (15.0 * ln1pyd) / 2.0) + trilog(1.0 / (2.0 - myi * eta)) * (6.0 * log(-1.0 + myi * eta) - 12.0 * log((myi + eta) / (2.0 * myi + eta)) - 11.0 * ln1myd - 2.0 * log(-yd) - 5.0 * ln1pyd) + trilog((1.0 + yd) / 2.0) * (10.0 * log(-yd) - 5.0 * ln1pyd) + li3half * (8.0 * log(1.0 - myi * xd) + 8.0 * log(1.0 + myi * xd) + 16.0 * log((-myi) * xd) + 16.0 * log(myi * xd) - 5.0 * ln1myd - 10.0 * log(-yd) - 10.0 * log(yd) - 5.0 * ln1pyd)
                + trilog(-myi / (myi + eta)) * (-28.0 * log(1.0 - myi * xd) - 28.0 * log(1.0 + myi * xd) - (3.0 * ln1pyd) / 2.0) - 8.0 * trilog(1.0 + 1.0 / (1.0 - myi * eta)) * ln1pyd + (15.0 * trilog((myi + eta) / (myi + eta - myi * yd)) * ln1pyd) / 2.0 + 7.0 * trilog((2.0 * myi + eta) / (myi + eta - myi * yd)) * ln1pyd + 10.0 * trilog(-ydinv) * ln1pyd - 5.0 * trilog((-1.0 + yd) / (2.0 * yd)) * ln1pyd - (15.0 * trilog(-yd) * ln1pyd) / 2.0 + (27.0 * trilog((myi * yd) / (myi + eta)) * ln1pyd) / 2.0 - (trilog(1.0 / (1.0 + yd)) * ln1pyd) / 2.0
                - (15.0 * trilog((eta - myi * (-1.0 + yd)) / ((myi + eta) * (1.0 + yd))) * ln1pyd) / 2.0 - 5.0 * trilog((-1.0 + yd) / (1.0 + yd)) * ln1pyd - 5.0 * trilog(yd / (1.0 + yd)) * ln1pyd - 2.0 * trilog(((2.0 * myi + eta) * yd) / ((myi + eta) * (1.0 + yd))) * ln1pyd + (15.0 * trilog(((-myi) * (1.0 + yd)) / (eta - myi * (-1.0 + yd))) * ln1pyd) / 2.0 - (15.0 * trilog(((myi + eta) * (1.0 + yd)) / (eta - myi * (-1.0 + yd))) * ln1pyd) / 2.0 - 11.0 * trilog(((myi + eta) * (1.0 + yd)) / ((2.0 * myi + eta) * yd)) * ln1pyd + 7.0 * trilog(yd / (-1.0 + myi * eta + yd)) * ln1pyd
                - 7.0 * trilog(((2.0 - myi * eta) * yd) / (-1.0 + myi * eta + yd)) * ln1pyd + (11.0 * trilog((-1.0 + myi * eta + yd) / yd) * ln1pyd) / 2.0 - 5.0 * trilog((-1.0 + myi * eta + yd) / ((2.0 - myi * eta) * yd)) * ln1pyd + (5.0 * trilog((-1.0 + myi * eta + yd) / (1.0 + yd)) * ln1pyd) / 2.0 + 8.0 * trilog(1.0 - (myi * yd) / (myi + eta)) * ln1pyd + 5.0 * dilog((-1.0 + yd) / (2.0 * yd)) * log((1.0 - yd) / 2.0) * ln1pyd + 5.0 * dilog((-1.0 + yd) / (1.0 + yd)) * log((1.0 - yd) / 2.0) * ln1pyd + (7.0 * pisqu * log(-1.0 / (1.0 - myi * eta - yd)) * ln1pyd) / 6.0 + (7.0 * power_of<3>(log(-1.0 / (1.0 - myi * eta - yd))) * ln1pyd) / 6.0
                + 5.0 * dilog((-1.0 + myi * eta + yd) / ((2.0 - myi * eta) * yd)) * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd + (7.0 * power_of<3>(log(-ydinv)) * ln1pyd) / 12.0 - (5.0 * power_of<2>(log((1.0 - yd) / 2.0)) * log(ydinv) * ln1pyd) / 2.0 + 5.0 * dilog(yd / (1.0 + yd)) * log(-yd) * ln1pyd + 2.0 * dilog(((2.0 * myi + eta) * yd) / ((myi + eta) * (1.0 + yd))) * log(-yd) * ln1pyd - 7.0 * dilog(yd / (-1.0 + myi * eta + yd)) * log(-yd) * ln1pyd + 7.0 * dilog(((2.0 - myi * eta) * yd) / (-1.0 + myi * eta + yd)) * log(-yd) * ln1pyd + 4.0 * dilog(1.0 + 1.0 / (1.0 - myi * eta)) * power_of<2>(ln1pyd)
                - (15.0 * dilog(((-myi) * (1.0 + yd)) / (eta - myi * (-1.0 + yd))) * power_of<2>(ln1pyd)) / 2.0 + (15.0 * dilog(((myi + eta) * (1.0 + yd)) / (eta - myi * (-1.0 + yd))) * power_of<2>(ln1pyd)) / 2.0 + 11.0 * dilog(((myi + eta) * (1.0 + yd)) / ((2.0 * myi + eta) * yd)) * power_of<2>(ln1pyd) + trilog(1.0 + ydinv) * (5.0 * ln1myd + (7.0 * ln1pyd) / 2.0) + trilog((-1.0 + yd) / yd) * ((7.0 * ln1myd) / 2.0 + 5.0 * ln1pyd) + trilog((myi * (1.0 + yd)) / (2.0 * myi + eta)) * (2.0 * log(-1.0 + myi * eta) - 8.0 * log((myi + eta) / (2.0 * myi + eta)) + 2.0 * log(-yd) + 8.0 * ln1pyd)
                + dilog((-1.0 + yd) / yd) * ((-7.0 * power_of<2>(ln1myd)) / 2.0 - 5.0 * log((1.0 - yd) / 2.0) * ln1pyd) + li2half * (8.0 * dilog(1.0 - myi * xd) + 8.0 * dilog(1.0 + myi * xd) - 5.0 * dilog(1.0 - yd) - 5.0 * dilog(1.0 + yd) + 16.0 * log(1.0 + myi * xd) * log((-myi) * xd) + 16.0 * log(1.0 - myi * xd) * log(myi * xd) - 10.0 * ln1myd * log(yd) - 10.0 * log(-yd) * ln1pyd) + dilog((myi * (1.0 + yd)) / (2.0 * myi + eta)) * ((-5.0 * pisqu) / 6.0 - 11.0 * power_of<2>(ln1pyd)) + dilog(1.0 - (myi * yd) / (myi + eta)) * (-8.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd - 4.0 * power_of<2>(ln1pyd))
                + dilog(1.0 + ydinv) * (-5.0 * ln1myd * log((1.0 + yd) / 2.0) - (7.0 * power_of<2>(ln1pyd)) / 2.0) + dilog((myi * yd) / (myi + eta)) * (-2.0 * log(-yd) * ln1pyd - power_of<2>(ln1pyd)) + dilog(-myi / (myi + eta)) * (8.0 * power_of<2>(log(1.0 - myi * xd)) + 8.0 * power_of<2>(log(1.0 + myi * xd)) + (3.0 * power_of<2>(ln1pyd)) / 2.0) + log(-ydinv) * ((7.0 * pisqu * ln1pyd) / 12.0 - (7.0 * power_of<3>(ln1pyd)) / 4.0) + trilog(1.0 + yd) * (-2.0 * log(-1.0 + myi * eta) + 8.0 * log((myi + eta) / (2.0 * myi + eta)) + 12.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) + ln1pyd - 12.0 * log(1.0 - (myi * yd) / (myi + eta)))
                + dilog((-1.0 + myi * eta + yd) / yd) * (-5.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd - (ln1pyd * log(1.0 - (myi * yd) / (myi + eta))) / 2.0) + dilog((eta - myi * (-1.0 + yd)) / ((myi + eta) * (1.0 + yd))) * (8.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd - (ln1pyd * log(1.0 - (myi * yd) / (myi + eta))) / 2.0) + dilog((-1.0 + myi * eta + yd) / (1.0 + yd)) * (-3.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd + (ln1pyd * log(1.0 - (myi * yd) / (myi + eta))) / 2.0)
                + dilog(-1.0 + myi * eta) * (-12.0 * log((myi + eta - xd) / (myi + eta)) * log(1.0 - myi * xd) - 12.0 * log(1.0 + myi * xd) * log((myi + eta + xd) / (myi + eta)) - (15.0 * ln1pyd * log(1.0 - (myi * yd) / (myi + eta))) / 2.0 - (15.0 * ln1myd * log(1.0 + (myi * yd) / (myi + eta))) / 2.0) + dilog((1.0 - myi * eta + yd) / yd) * ln1myd * ((-0.5) * log(1.0 + (myi * yd) / (myi + eta)) - 5.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) + dilog((1.0 - myi * eta + yd) / (-1.0 + yd)) * ln1myd * (log(1.0 + (myi * yd) / (myi + eta)) / 2.0 - 3.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)))
                + 5.0 * dilog((eta + myi * (1.0 + yd)) / ((2.0 * myi + eta) * yd)) * ln1myd * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)) + dilog(-((eta + myi * (1.0 + yd)) / ((myi + eta) * (-1.0 + yd)))) * ln1myd * ((-0.5) * log(1.0 + (myi * yd) / (myi + eta)) + 8.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) + trilog(1.0 - yd) * (-2.0 * log(-1.0 + myi * eta) + 8.0 * log((myi + eta) / (2.0 * myi + eta)) + ln1myd - 12.0 * log(1.0 + (myi * yd) / (myi + eta)) + 12.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) + dilog(1.0 + (myi * yd) / (myi + eta)) * (-4.0 * power_of<2>(ln1myd) - 8.0 * ln1myd * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)))
                + power_of<3>(log(1.0 - myi * xd)) * (-6.0 * log((2.0 * myi + eta) / (myi + eta - xd)) + 6.0 * log(-myi / xd) + 6.0 * log((myi * (2.0 * myi + eta) * xd) / (myi + eta - xd)) - (4.0 * myi) * M_PI * my_sign(std::real(xd)) * T(1.0, (myi + eta - xd) / (myi + eta), 1.0 - myi * xd)) + (24.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * log(-1.0 + myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta) + dilog(1.0 - myi * xd) * (-8.0 * dilog(0.5 - (myi / 2.0) * xd) + 20.0 * dilog((myi + xd) / (2.0 * myi + eta)) + 8.0 * log((myi + eta - xd) / (myi + eta)) * log(1.0 - myi * xd) - (16.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta))
                + log(myi * xd) * (4.0 * power_of<2>(log(1.0)) * log((myi + eta) / (2.0 * myi + eta)) + (16.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta)) + (24.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * log(-1.0 + myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta) + dilog(1.0 + myi * xd) * (20.0 * dilog((myi - xd) / (2.0 * myi + eta)) - 8.0 * dilog((1.0 + myi * xd) / 2.0) + 8.0 * log(1.0 + myi * xd) * log((myi + eta + xd) / (myi + eta)) - (16.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta))
                + log((-myi) * xd) * (4.0 * power_of<2>(log(1.0)) * log((myi + eta) / (2.0 * myi + eta)) + (16.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta)) + power_of<2>(log(1.0 + myi * xd)) * (-8.0 * log((-myi) * xd) * log((myi + eta + xd) / (myi + eta)) - 4.0 * log(xd) * log((myi + eta + xd) / (myi + eta)) - (24.0 * myi) * M_PI * log(-1.0 + myi * eta) * my_sign(std::real(1.0 / (myi - xd))) * T(1.0, (-myi) * xd, -1.0 + myi * eta)) + power_of<2>(log(1.0 - myi * xd)) * (log((myi + eta - xd) / (myi + eta)) * (-8.0 * log(myi * xd) - 4.0 * log(xd)) - (24.0 * myi) * M_PI * log(-1.0 + myi * eta) * my_sign(std::real(1.0 / (myi + xd))) * T(1.0, myi * xd, -1.0 + myi * eta))
                + log(1.0 - myi * xd) * (2.0 * pisqu * log(myi / (myi + eta - xd)) + 2.0 * power_of<3>(log(myi / (myi + eta - xd))) - 2.0 * pisqu * log(-myi / xd) - 2.0 * power_of<3>(log(-myi / xd)) - (4.0 * pisqu * log((2.0 * myi) * xdinv)) / 3.0 - (4.0 * power_of<3>(log((2.0 * myi) * xdinv))) / 3.0 + ((-2.0 * pisqu) / 3.0 + 2.0 * power_of<2>(log((myi + eta - xd) / (myi + eta))) - 4.0 * power_of<2>(log((myi + eta - xd) / (2.0 * myi + eta)))) * log((myi + eta) * xdinv) - (2.0 * power_of<3>(log((myi + eta) * xdinv))) / 3.0 + (4.0 * pisqu * log((2.0 * myi + eta) * xdinv)) / 3.0 + (4.0 * power_of<3>(log((2.0 * myi + eta) * xdinv))) / 3.0 - 12.0 * log((myi + eta - xd) / (myi + eta)) * power_of<2>(log(myi * xd)) + (4.0 * pisqu * log((2.0 * myi) / (myi + xd))) / 3.0 + (4.0 * power_of<3>(log((2.0 * myi) / (myi + xd)))) / 3.0
                + (2.0 * pisqu * log((myi + eta) / (myi + xd))) / 3.0 + (2.0 * power_of<3>(log((myi + eta) / (myi + xd)))) / 3.0 - (4.0 * pisqu * log((2.0 * myi + eta) / (myi + xd))) / 3.0 - (4.0 * power_of<3>(log((2.0 * myi + eta) / (myi + xd)))) / 3.0 - 4.0 * pisqu * log((myi * (2.0 * myi + eta)) / ((myi + eta) * (myi + xd))) - 4.0 * power_of<3>(log((myi * (2.0 * myi + eta)) / ((myi + eta) * (myi + xd)))) + power_of<2>(log((1.0 + myi * xd) / 2.0)) * (4.0 * log(myi / xd) - 4.0 * log((2.0 * myi) / (myi + xd)) - 4.0 * log((myi + xd) / (2.0 * xd))) - (8.0 * myi) * M_PI * H1(2.0 - myi * eta, (2.0 * myi + eta) / (myi + xd)) * power_of<2>(log(-(xd / (2.0 * myi + eta)))) * my_sign(imag((2.0 * myi + eta) / (myi + xd)))
                - (12.0 * myi) * M_PI * H1(-myi / (myi + eta), -myi / xd) * power_of<2>(log(myi * (myi + eta - xd))) * my_sign(-std::real(xdinv)) - (4.0 * myi) * M_PI * H1(-1.0 + myi * eta, (myi + eta) * xdinv) * power_of<2>(log(-((myi + xd) / (myi + eta)))) * my_sign(std::real((1.0 - myi * eta) * xdinv)) - (24.0 * myi) * M_PI * H1(myi / (2.0 * myi + eta), myi / (myi + xd)) * power_of<2>(log(1.0 - myi * eta + myi * xd)) * my_sign(std::real(1.0 / (myi + xd))) + (24.0 * myi) * M_PI * H1((2.0 * myi + eta) / (myi + xd), myi / (myi + xd)) * power_of<2>(log((myi * (myi + eta) * (myi + xd)) / (2.0 * myi + eta))) * my_sign(std::real(1.0 / (myi + xd)))
                + power_of<2>(log(myi * xd)) * (-12.0 * log((myi + eta) / (myi + eta - xd)) + 12.0 * log((myi * (myi + eta - xd)) / ((myi + eta) * (myi + xd))) + 12.0 * log((myi + eta + xd - myi * eta * xd) / (myi + eta - xd)) + (8.0 * myi) * M_PI * my_sign(std::real(xd)) * T(1.0, (myi + eta - xd) / (2.0 * myi + eta), myi * xd)) - (16.0 * myi) * M_PI * log(2.0 - myi * eta) * log(myi * xd) * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta) + power_of<2>(log((myi + eta - xd) / (myi + eta))) * (-2.0 * log((2.0 * myi + eta) / (myi + xd)) + 2.0 * log(((2.0 * myi + eta) * xd) / ((myi + eta) * (myi + xd))) - (12.0 * myi) * M_PI * my_sign(imag(xd / (myi + eta))) * T(1.0, 1.0 - myi * xd, (myi + eta - xd) / (myi + eta)))
                - (24.0 * myi) * M_PI * power_of<2>(log(-1.0 + myi * eta)) * my_sign(std::real(eta)) * T(1.0, myi * xd, -1.0 + myi * eta) + power_of<2>(log((myi + eta - xd) / (2.0 * myi + eta))) * (4.0 * log((2.0 * myi + eta) / (myi + xd)) + 4.0 * log(((myi + eta) * (myi + xd)) / ((2.0 * myi + eta) * xd)) - (24.0 * myi) * M_PI * my_sign(imag((myi + xd) / (2.0 * myi + eta))) * T(1.0, myi * xd, (myi + eta - xd) / (2.0 * myi + eta)))) + power_of<3>(log(1.0 + myi * xd)) * (6.0 * log(myi / xd) - 6.0 * log((2.0 * myi + eta) / (myi + eta + xd)) + 6.0 * log(((2.0 - myi * eta) * xd) / (myi + eta + xd)) - (4.0 * myi) * M_PI * my_sign(-std::real(xd)) * T(1.0, (myi + eta + xd) / (myi + eta), 1.0 + myi * xd))
                + log(1.0 + myi * xd) * ((-4.0 * power_of<3>(log((2.0 * myi + eta) / (myi - xd)))) / 3.0 + ((4.0 * pisqu) / 3.0 - 4.0 * power_of<2>(log(0.5 - (myi / 2.0) * xd))) * log(2.0 / (1.0 + myi * xd)) + (4.0 * power_of<3>(log(2.0 / (1.0 + myi * xd)))) / 3.0 - 2.0 * pisqu * log(myi / xd) - 2.0 * power_of<3>(log(myi / xd)) - (4.0 * pisqu * log((-2.0 * myi) * xdinv)) / 3.0 - (4.0 * power_of<3>(log((-2.0 * myi) * xdinv))) / 3.0 - (2.0 * power_of<3>(log(-((myi + eta) * xdinv)))) / 3.0 + (4.0 * pisqu * log(-((2.0 * myi + eta) * xdinv))) / 3.0 + (4.0 * power_of<3>(log(-((2.0 * myi + eta) * xdinv)))) / 3.0 - 4.0 * pisqu * log((2.0 - myi * eta) / ((myi + eta) * (-myi + xd))) - 4.0 * power_of<3>(log((2.0 - myi * eta) / ((myi + eta) * (-myi + xd)))) + power_of<2>(log(0.5 - (myi / 2.0) * xd)) * (4.0 * log(-myi / xd) - 4.0 * log((-myi + xd) / (2.0 * xd)))
                + 4.0 * pisqu * log(-myi / (myi + eta + xd)) + 4.0 * power_of<3>(log(-myi / (myi + eta + xd))) + 2.0 * pisqu * log(myi / (myi + eta + xd)) + 2.0 * power_of<3>(log(myi / (myi + eta + xd))) + log(-((myi + eta) * xdinv)) * ((-2.0 * pisqu) / 3.0 + 2.0 * power_of<2>(log((myi + eta + xd) / (myi + eta))) - 4.0 * power_of<2>(log((myi + eta + xd) / (2.0 * myi + eta)))) + log((2.0 * myi + eta) / (myi - xd)) * ((-4.0 * pisqu) / 3.0 - 2.0 * power_of<2>(log((myi + eta + xd) / (myi + eta))) + 4.0 * power_of<2>(log((myi + eta + xd) / (2.0 * myi + eta)))) - (8.0 * myi) * M_PI * H1(2.0 - myi * eta, (2.0 * myi + eta) / (myi - xd)) * power_of<2>(log(xd / (2.0 * myi + eta))) * my_sign(imag((2.0 * myi + eta) / (myi - xd)))
                + (24.0 * myi) * M_PI * H1((2.0 * myi + eta) / (myi - xd), -myi / (-myi + xd)) * power_of<2>(log(((1.0 - myi * eta) * (-myi + xd)) / (2.0 * myi + eta))) * my_sign(std::real(1.0 / (myi - xd))) - (24.0 * myi) * M_PI * H1(myi / (2.0 * myi + eta), -myi / (-myi + xd)) * power_of<2>(log((-myi) * (myi + eta + xd))) * my_sign(std::real(1.0 / (myi - xd))) - (12.0 * myi) * M_PI * H1(-myi / (myi + eta), myi / xd) * power_of<2>(log(myi * (myi + eta + xd))) * my_sign(std::real(xdinv)) - (4.0 * myi) * M_PI * H1(-1.0 + myi * eta, -((myi + eta) * xdinv)) * power_of<2>(log((-myi + xd) / (myi + eta))) * my_sign(-std::real((1.0 - myi * eta) * xdinv)) - (16.0 * myi) * M_PI * log(2.0 - myi * eta) * log((-myi) * xd) * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta)
                + power_of<2>(log((myi + eta + xd) / (myi + eta))) * (2.0 * log(((2.0 * myi + eta) * xd) / ((myi + eta) * (-myi + xd))) - (12.0 * myi) * M_PI * my_sign(-imag(xd / (myi + eta))) * T(1.0, 1.0 + myi * xd, (myi + eta + xd) / (myi + eta))) - (24.0 * myi) * M_PI * power_of<2>(log(-1.0 + myi * eta)) * my_sign(std::real(eta)) * T(1.0, (-myi) * xd, -1.0 + myi * eta) + power_of<2>(log((myi + eta + xd) / (2.0 * myi + eta))) * (4.0 * log(((myi + eta) * (-myi + xd)) / ((2.0 * myi + eta) * xd)) - (24.0 * myi) * M_PI * my_sign(imag((myi - xd) / (2.0 * myi + eta))) * T(1.0, (-myi) * xd, (myi + eta + xd) / (2.0 * myi + eta)))
                + power_of<2>(log((-myi) * xd)) * (-12.0 * log((myi + eta) / (myi + eta + xd)) + 12.0 * log(((myi + eta) * (1.0 + myi * xd)) / (myi + eta + xd)) - 12.0 * log((myi + eta + xd) / (myi + eta)) + 12.0 * log(((-myi) * (myi + eta + xd)) / ((myi + eta) * (-myi + xd))) + (8.0 * myi) * M_PI * my_sign(-std::real(xd)) * T(1.0, (myi + eta + xd) / (2.0 * myi + eta), (-myi) * xd))) + ((5.0 * myi) / 3.0) * power_of<3>(M_PI) * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta) - (6.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * log(-1.0 + myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta)
                + dilog(yd) * (ln1myd * ((9.0 * log(1.0 + (myi * yd) / (myi + eta))) / 2.0 + 11.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) + (22.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(imydinv) * T(1.0, 1.0 - yd, 2.0 - myi * eta)) + dilog(1.0 - yd) * (5.0 * dilog((1.0 - yd) / 2.0) + 7.0 * dilog((-1.0 + yd) / (-2.0 + myi * eta)) + 12.0 * ln1myd * log(1.0 + (myi * yd) / (myi + eta)) + (6.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta)) + log(yd) * ((5.0 * power_of<2>(log(1.0)) * log((myi + eta) / (2.0 * myi + eta))) / 2.0 + (2.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta))
                + power_of<2>(log(-yd)) * ln1pyd * ((-7.0 * log((myi + eta) / (myi + eta - myi * yd))) / 2.0 + (5.0 * log(1.0 / (1.0 + yd))) / 2.0 + log((eta - myi * (-1.0 + yd)) / ((myi + eta) * (1.0 + yd))) + (7.0 * log(((myi + eta) * (1.0 + yd)) / (eta - myi * (-1.0 + yd)))) / 2.0 - log(1.0 - (myi * yd) / (myi + eta)) + (5.0 * myi) * M_PI * my_sign(-imag(yd)) * T(1.0, (myi + eta - myi * yd) / (2.0 * myi + eta), -yd))
                + power_of<2>(ln1pyd) * (-4.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * log((myi * yd) / (myi + eta)) - (8.0 * myi) * M_PI * log((myi + eta) / (2.0 * myi + eta)) * my_sign(imag((2.0 - myi * eta) / (1.0 + yd))) * T(1.0, (myi + eta - myi * yd) / (2.0 * myi + eta), (myi + eta) / (2.0 * myi + eta)) - (2.0 * myi) * M_PI * log(-1.0 + myi * eta) * my_sign(imag(1.0 / (1.0 + yd))) * T(1.0, -yd, -1.0 + myi * eta)) + ((5.0 * myi) / 3.0) * power_of<3>(M_PI) * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta) - (6.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * log(-1.0 + myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta)
                + dilog(-yd) * (11.0 * dilog((myi * (1.0 + yd)) / (2.0 * myi + eta)) + 11.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd + (9.0 * ln1pyd * log(1.0 - (myi * yd) / (myi + eta))) / 2.0 + (22.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(-imydinv) * T(1.0, 1.0 + yd, 2.0 - myi * eta)) + trilog(2.0 - myi * eta) * (36.0 * log(-1.0 + myi * eta) - 24.0 * log(1.0 - myi * xd) - 24.0 * log(1.0 + myi * xd) - 7.0 * ln1myd - 7.0 * ln1pyd - (48.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta) - (48.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta) - (24.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta)
                - (24.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta)) + dilog(1.0 + yd) * (5.0 * dilog((1.0 + yd) / 2.0) + 7.0 * dilog((myi * (1.0 + yd)) / (2.0 * myi + eta)) + 12.0 * ln1pyd * log(1.0 - (myi * yd) / (myi + eta)) + (6.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta)) + dilog(2.0 - myi * eta) * (-18.0 * pisqu - 12.0 * dilog(1.0 - myi * xd) - 12.0 * dilog(1.0 + myi * xd) - dilog(1.0 - yd) - dilog(1.0 + yd) - 18.0 * power_of<2>(log(-2.0 + myi * eta)) - 24.0 * log((myi + eta - xd) / (2.0 * myi + eta)) * log(1.0 - myi * xd) - 24.0 * log(1.0 + myi * xd) * log((myi + eta + xd) / (2.0 * myi + eta))
                - 7.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * ln1pyd - 7.0 * ln1myd * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)) + (64.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta) + (64.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta) + (8.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta) + (8.0 * myi) * M_PI * log(2.0 - myi * eta) * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta))
                + log(-yd) * ((5.0 * power_of<2>(log(1.0)) * log((myi + eta) / (2.0 * myi + eta))) / 2.0 + 5.0 * power_of<2>(ln1pyd) * log(1.0 - (myi * yd) / (myi + eta)) + (2.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta) + (6.0 * myi) * M_PI * log(2.0 - myi * eta) * ln1pyd * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta)) + ln1pyd * ((5.0 * pisqu * log(1.0 / (1.0 - myi * eta - yd))) / 4.0 + (5.0 * power_of<3>(log(1.0 / (1.0 - myi * eta - yd)))) / 4.0 - (5.0 * pisqu * log((myi + eta - myi * yd) / (2.0 * myi + eta))) / 6.0 + (5.0 * pisqu * log(2.0 / yd)) / 6.0 + (5.0 * power_of<3>(log(2.0 / yd))) / 6.0 + power_of<3>(log((1.0 - myi * eta) / yd)) / 12.0 + (5.0 * pisqu * log((2.0 - myi * eta) / yd)) / 6.0
                + (5.0 * power_of<3>(log((2.0 - myi * eta) / yd))) / 6.0 - (5.0 * pisqu * log(1.0 / (1.0 + yd))) / 6.0 - (5.0 * power_of<3>(log(1.0 / (1.0 + yd)))) / 6.0 - (5.0 * pisqu * log(2.0 / (1.0 + yd))) / 6.0 - (5.0 * power_of<3>(log(2.0 / (1.0 + yd)))) / 6.0 - (pisqu * log((1.0 - myi * eta) / (1.0 + yd))) / 12.0 - power_of<3>(log((1.0 - myi * eta) / (1.0 + yd))) / 12.0 + power_of<3>(log((2.0 - myi * eta) / (1.0 + yd))) / 2.0 - (4.0 * pisqu * log(-((2.0 * myi + eta) / ((myi + eta) * (1.0 + yd))))) / 3.0 - (4.0 * power_of<3>(log(-((2.0 * myi + eta) / ((myi + eta) * (1.0 + yd)))))) / 3.0 - (pisqu * log((2.0 * myi + eta) / ((myi + eta) * (1.0 + yd)))) / 3.0 - power_of<3>(log((2.0 * myi + eta) / ((myi + eta) * (1.0 + yd)))) / 3.0
                + power_of<2>(log((1.0 - yd) / 2.0)) * ((5.0 * log(2.0 / (1.0 + yd))) / 2.0 + (5.0 * log((1.0 + yd) / (2.0 * yd))) / 2.0) - (11.0 * pisqu * log(-((myi + eta) / ((2.0 * myi) * yd + eta * yd)))) / 6.0 - (11.0 * power_of<3>(log(-((myi + eta) / ((2.0 * myi) * yd + eta * yd))))) / 6.0 - (log(((2.0 * myi + eta) * yd) / ((myi + eta) * (1.0 + yd))) * power_of<2>(log(1.0 - (myi * yd) / (myi + eta)))) / 4.0 + log((1.0 - myi * eta) / yd) * (pisqu / 12.0 - power_of<2>(log(1.0 - (myi * yd) / (myi + eta))) / 4.0) + log((2.0 - myi * eta) / (1.0 + yd)) * (pisqu / 2.0 + power_of<2>(log(1.0 - (myi * yd) / (myi + eta))) / 4.0) + (11.0 * myi) * M_PI * H1((1.0 - myi * eta) / yd, -ydinv) * power_of<2>(log(((2.0 * myi + eta) * yd) / (myi + eta))) * my_sign(-imydinv)
                - ((15.0 * myi) / 2.0) * M_PI * H1(-myi / (myi + eta), -ydinv) * power_of<2>(log(-1.0 + myi * eta + yd)) * my_sign(-imydinv) + (myi / 2.0) * M_PI * H1(-1.0 + myi * eta, (1.0 - myi * eta) / yd) * power_of<2>(log(((-myi) * (1.0 + yd)) / (myi + eta))) * my_sign(imag((1.0 - myi * eta) / yd)) - (7.0 * myi) * M_PI * H1(1.0 / (2.0 - myi * eta), 1.0 / (1.0 + yd)) * power_of<2>(log(1.0 - myi * eta - yd)) * my_sign(imag(1.0 / (1.0 + yd))) + (2.0 * myi) * M_PI * H1((2.0 - myi * eta) / (1.0 + yd), 1.0 / (1.0 + yd)) * power_of<2>(log(-(((myi + eta) * (1.0 + yd)) / (2.0 * myi + eta)))) * my_sign(imag(1.0 / (1.0 + yd))) - (5.0 * myi) * M_PI * H1(2.0 - myi * eta, (2.0 - myi * eta) / (1.0 + yd)) * power_of<2>(log(((-myi) * yd) / (2.0 * myi + eta))) * my_sign(imag((2.0 - myi * eta) / (1.0 + yd)))
                + (8.0 * myi) * M_PI * H1(1.0 / (1.0 + yd), (2.0 - myi * eta) / (1.0 + yd)) * power_of<2>(log(((myi + eta) * (1.0 + yd)) / (2.0 * myi + eta))) * my_sign(imag((2.0 - myi * eta) / (1.0 + yd))) - (8.0 * myi) * M_PI * power_of<2>(log((myi + eta) / (2.0 * myi + eta))) * my_sign(-std::real(1.0 / (2.0 * myi + eta))) * T(1.0, (myi + eta - myi * yd) / (2.0 * myi + eta), (myi + eta) / (2.0 * myi + eta)) - (2.0 * myi) * M_PI * power_of<2>(log(-1.0 + myi * eta)) * my_sign(std::real(eta)) * T(1.0, -yd, -1.0 + myi * eta)
                + power_of<2>(log((myi + eta - myi * yd) / (2.0 * myi + eta))) * ((-5.0 * log((1.0 - myi * eta) / yd)) / 2.0 - 4.0 * log((myi * yd) / (myi + eta)) - (3.0 * log((2.0 - myi * eta) / (1.0 + yd))) / 2.0 + 4.0 * log(((2.0 * myi + eta) * yd) / ((myi + eta) * (1.0 + yd))) + (5.0 * log(((myi + eta) * (1.0 + yd)) / ((2.0 * myi + eta) * yd))) / 2.0 - (7.0 * myi) * M_PI * my_sign(std::real((1.0 + yd) / (2.0 * myi + eta))) * T(1.0, -yd, (myi + eta - myi * yd) / (2.0 * myi + eta))) + (11.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta) - ((15.0 * myi) / 2.0) * M_PI * power_of<2>(log(1.0 - (myi * yd) / (myi + eta))) * my_sign(std::real(yd / (myi + eta))) * T(1.0, 1.0 + yd, 1.0 - (myi * yd) / (myi + eta)))
                + power_of<3>(ln1pyd) * ((-15.0 * log((2.0 * myi + eta) / (myi + eta - myi * yd))) / 4.0 - (11.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta))) / 2.0 + (15.0 * log(((2.0 - myi * eta) * yd) / (-1.0 + myi * eta + yd))) / 4.0 + (11.0 * log((-1.0 + myi * eta + yd) / ((2.0 - myi * eta) * yd))) / 2.0 + (myi / 2.0) * M_PI * my_sign(-imag(yd)) * T(1.0, 1.0 - (myi * yd) / (myi + eta), 1.0 + yd))
                + power_of<3>(ln1myd) * ((-7.0 * log(ydinv)) / 4.0 - (15.0 * log((2.0 * myi + eta) / (eta + myi * (1.0 + yd)))) / 4.0 + (15.0 * log(((2.0 * myi + eta) * yd) / (eta + myi * (1.0 + yd)))) / 4.0 - (11.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) / 2.0 + (11.0 * log((eta + myi * (1.0 + yd)) / ((2.0 * myi + eta) * yd))) / 2.0 + (myi / 2.0) * M_PI * my_sign(imag(yd)) * T(1.0, 1.0 + (myi * yd) / (myi + eta), 1.0 - yd))
                + power_of<2>(ln1myd) * (5.0 * log(yd) * log(1.0 + (myi * yd) / (myi + eta)) - 4.0 * log(yd / (-1.0 + myi * eta)) * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)) - (2.0 * myi) * M_PI * log(-1.0 + myi * eta) * my_sign(imag(1.0 / (1.0 - yd))) * T(1.0, yd, -1.0 + myi * eta) - (8.0 * myi) * M_PI * log((myi + eta) / (2.0 * myi + eta)) * my_sign(std::real((2.0 * myi + eta) / (-1.0 + yd))) * T(1.0, (eta + myi * (1.0 + yd)) / (2.0 * myi + eta), (myi + eta) / (2.0 * myi + eta)))
                + ln1myd * ((-5.0 * power_of<3>(log(-2.0 / (-1.0 + yd)))) / 6.0 - (pisqu * log((myi * (myi + eta)) / (-1.0 + yd))) / 12.0 - power_of<3>(log((myi * (myi + eta)) / (-1.0 + yd))) / 12.0 + power_of<3>(log((myi * (2.0 * myi + eta)) / (-1.0 + yd))) / 2.0 - (pisqu * log(-((2.0 * myi + eta) / ((myi + eta) * (-1.0 + yd))))) / 3.0 - power_of<3>(log(-((2.0 * myi + eta) / ((myi + eta) * (-1.0 + yd))))) / 3.0 - (4.0 * pisqu * log((2.0 * myi + eta) / ((myi + eta) * (-1.0 + yd)))) / 3.0 - (4.0 * power_of<3>(log((2.0 * myi + eta) / ((myi + eta) * (-1.0 + yd))))) / 3.0 + (5.0 * pisqu * log(-2.0 / yd)) / 6.0 + (5.0 * power_of<3>(log(-2.0 / yd))) / 6.0 + (7.0 * pisqu * log(ydinv)) / 12.0 + (7.0 * power_of<3>(log(ydinv))) / 12.0 + power_of<3>(log((myi * (myi + eta)) / yd)) / 12.0
                + (5.0 * pisqu * log((myi * (2.0 * myi + eta)) / yd)) / 6.0 + (5.0 * power_of<3>(log((myi * (2.0 * myi + eta)) / yd))) / 6.0 + ((-5.0 * log(-ydinv)) / 2.0 + (5.0 * log((-1.0 + yd) / (2.0 * yd))) / 2.0) * power_of<2>(log((1.0 + yd) / 2.0)) + log(-2.0 / (-1.0 + yd)) * ((-5.0 * pisqu) / 6.0 + (5.0 * power_of<2>(log((1.0 + yd) / 2.0))) / 2.0) + (7.0 * pisqu * log(-1.0 / (1.0 - myi * eta + yd))) / 6.0 + (7.0 * power_of<3>(log(-1.0 / (1.0 - myi * eta + yd)))) / 6.0 - (11.0 * pisqu * log((myi + eta) / ((2.0 * myi) * yd + eta * yd))) / 6.0 - (11.0 * power_of<3>(log((myi + eta) / ((2.0 * myi) * yd + eta * yd)))) / 6.0 + (5.0 * pisqu * log(myi / (eta + myi * (1.0 + yd)))) / 4.0 + (5.0 * power_of<3>(log(myi / (eta + myi * (1.0 + yd))))) / 4.0
                - (5.0 * pisqu * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) / 6.0 + 4.0 * log(((2.0 * myi + eta) * yd) / ((myi + eta) * (-1.0 + yd))) * power_of<2>(log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) + log((myi * (myi + eta)) / yd) * (pisqu / 12.0 - power_of<2>(log(1.0 + (myi * yd) / (myi + eta))) / 4.0 - (5.0 * power_of<2>(log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)))) / 2.0) + log((myi * (2.0 * myi + eta)) / (-1.0 + yd)) * (pisqu / 2.0 + power_of<2>(log(1.0 + (myi * yd) / (myi + eta))) / 4.0 - (3.0 * power_of<2>(log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)))) / 2.0) + (2.0 * myi) * M_PI * H1((myi * (2.0 * myi + eta)) / (-1.0 + yd), 1.0 / (1.0 - yd)) * power_of<2>(log(((myi + eta) * (-1.0 + yd)) / (2.0 * myi + eta))) * my_sign(imag(1.0 / (1.0 - yd)))
                - (7.0 * myi) * M_PI * H1(myi / (2.0 * myi + eta), 1.0 / (1.0 - yd)) * power_of<2>(log(1.0 - myi * eta + yd)) * my_sign(imag(1.0 / (1.0 - yd))) - ((15.0 * myi) / 2.0) * M_PI * H1(1.0 / (-1.0 + myi * eta), ydinv) * power_of<2>(log(-1.0 + myi * eta - yd)) * my_sign(imydinv) + (11.0 * myi) * M_PI * H1((myi * (myi + eta)) / yd, ydinv) * power_of<2>(log((-1.0 + 1.0 / (-1.0 + myi * eta)) * yd)) * my_sign(imydinv) + (8.0 * myi) * M_PI * H1(1.0 / (1.0 - yd), (myi * (2.0 * myi + eta)) / (-1.0 + yd)) * power_of<2>(log(-(((myi + eta) * (-1.0 + yd)) / (2.0 * myi + eta)))) * my_sign(std::real((2.0 * myi + eta) / (-1.0 + yd)))
                - (5.0 * myi) * M_PI * H1(2.0 - myi * eta, (myi * (2.0 * myi + eta)) / (-1.0 + yd)) * power_of<2>(log((myi * yd) / (2.0 * myi + eta))) * my_sign(std::real((2.0 * myi + eta) / (-1.0 + yd))) + (myi / 2.0) * M_PI * H1(-1.0 + myi * eta, (myi * (myi + eta)) / yd) * power_of<2>(log((myi * (-1.0 + yd)) / (myi + eta))) * my_sign(std::real((myi + eta) / yd)) + (11.0 * myi) * M_PI * power_of<2>(log(2.0 - myi * eta)) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta) + (6.0 * myi) * M_PI * log(2.0 - myi * eta) * log(yd) * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta) + power_of<2>(log(1.0 + (myi * yd) / (myi + eta))) * ((-1.0 / 4.0) * log(((2.0 * myi + eta) * yd) / ((myi + eta) * (-1.0 + yd))) - ((15.0 * myi) / 2.0) * M_PI * my_sign(-std::real(yd / (myi + eta))) * T(1.0, 1.0 - yd, 1.0 + (myi * yd) / (myi + eta)))
                - (2.0 * myi) * M_PI * power_of<2>(log(-1.0 + myi * eta)) * my_sign(std::real(eta)) * T(1.0, yd, -1.0 + myi * eta) + power_of<2>(log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) * ((5.0 * log(((myi + eta) * (-1.0 + yd)) / ((2.0 * myi + eta) * yd))) / 2.0 - 4.0 * log(yd / (-1.0 + myi * eta)) - (7.0 * myi) * M_PI * my_sign(imag((-1.0 + yd) / (-2.0 + myi * eta))) * T(1.0, yd, (eta + myi * (1.0 + yd)) / (2.0 * myi + eta))) - (8.0 * myi) * M_PI * power_of<2>(log((myi + eta) / (2.0 * myi + eta))) * my_sign(-std::real(1.0 / (2.0 * myi + eta))) * T(1.0, (eta + myi * (1.0 + yd)) / (2.0 * myi + eta), (myi + eta) / (2.0 * myi + eta))
                + power_of<2>(log(yd)) * (-log(1.0 + (myi * yd) / (myi + eta)) - (7.0 * log((myi + eta) / (eta + myi * (1.0 + yd)))) / 2.0 + (7.0 * log(-(((myi + eta) * (-1.0 + yd)) / (eta + myi * (1.0 + yd))))) / 2.0 + log(-((eta + myi * (1.0 + yd)) / ((myi + eta) * (-1.0 + yd)))) + (5.0 * myi) * M_PI * my_sign(imag(yd)) * T(1.0, (eta + myi * (1.0 + yd)) / (2.0 * myi + eta), yd))) + 72.0 * log((myi + eta) / (2.0 * myi + eta)) * zeta3 + 8.0 * log((myi + eta - xd) / (myi + eta)) * zeta3 - 24.0 * log((myi + eta - xd) / (2.0 * myi + eta)) * zeta3 + 8.0 * log((myi + eta + xd) / (myi + eta)) * zeta3 - 24.0 * log((myi + eta + xd) / (2.0 * myi + eta)) * zeta3
                - 12.0 * log((myi + eta - myi * yd) / (2.0 * myi + eta)) * zeta3 + 12.0 * log(1.0 - (myi * yd) / (myi + eta)) * zeta3 + 12.0 * log(1.0 + (myi * yd) / (myi + eta)) * zeta3 - 12.0 * log((eta + myi * (1.0 + yd)) / (2.0 * myi + eta)) * zeta3 + (48.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 - myi * xd, 2.0 - myi * eta) * zeta3 + (48.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 + myi * xd, 2.0 - myi * eta) * zeta3 + (24.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 - yd, 2.0 - myi * eta) * zeta3 + (24.0 * myi) * M_PI * my_sign(std::real(eta)) * T(1.0, 1.0 + yd, 2.0 - myi * eta) * zeta3;

            return w4Part1 + w4Part2 + w4Part3 + w4Part4 + w4Part5 + w4Part6 + w4HPLs;
        }
    }
}
